# -*- coding: utf-8 -*-
"""Ejercicio_Gestión_Ambulancias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nQuiHdlei7IXHd59xj4qHW2cL02VY9ns

Autor: Jairo Blanco
Codigo: 2024114040
Materia: Inteligencia Artificial
Tema: Agente Basado en Modelo
descripcion: Un hospital dispone de tres ambulancias.
El sistema debe asignar una ambulancia disponible a cada emergencia y
recordar las asignaciones para impedir que una misma unidad sea enviada simultáneamente a dos casos.

Definimos la creación del modelo base, que posteriormente se puede "entrenar" o actualizar.
"""

def crear_modelo()->dict:
  modelo = {
    "ambulancias": {"AMB-01": "disponible", "AMB-02": "disponible", "AMB-03": "disponible"},
    "asignaciones": {}
  }
  return modelo

"""Definimos ahora la funcion de tratado de parametros de entrada(percepcion)

"""

def percepcion(codigo_emergencia:str, prioridad:str, zona: str)->tuple[str,str,str]:
  return codigo_emergencia, prioridad, zona

"""ahora definimos la funcion para asignar una ambulancia y otra para liberar"""

def asignar_ambulancia(ambulancia:str ,percepcion: tuple[str,str,str], modelo:dict)->None:
  codigo_emergencia,_,_ = percepcion
  modelo["ambulancias"][ambulancia] = "ocupada"
  modelo["asignaciones"][codigo_emergencia] = ambulancia

def liberar_ambulancia(ambulancia:str, percepcion: tuple[str,str,str], modelo:dict )->None:
  codigo_emercengia,_,_ = percepcion
  modelo["ambulancias"][ambulancia] = "disponible"
  del modelo["asignaciones"][codigo_emercengia]

"""esta funcion busca la ambulancia disponible en el listado y la asigna, actualizando el modelo"""

def actualizar_modelo(modelo:dict, percepcion_actual:tuple[str,str,str])->None:
  for ambulancia, estado in modelo["ambulancias"].items():
      if estado == "disponible":
        asignar_ambulancia(ambulancia, percepcion_actual, modelo)
        break

"""luego definimos al modelo y su lógica"""

def agente_basado_modelo(percepcion_actual:tuple[str,str,str], modelo:dict)->None:
  codigo_emergencia, prioridad, zona = percepcion_actual
  codigo = codigo_emergencia.lower()
  if codigo in modelo["asignaciones"]: #si el codigo ya está en las asignaciones de alguna ambulancia se muestra en pantalla
    ambulancia = modelo["asignaciones"][codigo]
    print("La ambulancia", ambulancia, "se encuentra ya en la emergencia ", codigo)
    return
  if "disponible" in modelo["ambulancias"].values(): #verificamos si hay ambulancias disponibles
    for ambulancia, estado in modelo["ambulancias"].items():
      if estado == "disponible" : #si la hay buscamos el codigo de la primera que esté disponible y la asignamos
        asignar_ambulancia(ambulancia, percepcion_actual, modelo)
        break
  else:
    print("No hay ambulancias disponibles") #si no hay ambulancias disponibles no actualizamos nada del modelo
    return

"""definimos una funcion para mostrar el estado del modelo"""

def mostrar_estado(modelo:dict):
  print("Ambulancias:") #imprimimos ambulancias y su estado
  for ambulancia, estado in modelo["ambulancias"].items():
    print(f"{ambulancia}: {estado}")
  if len(modelo["asignaciones"]) > 0: #imprimimos asignaciones si existen, sino imprimimos que no hay
    print("Asignaciones:")
    for codigo, ambulancia in modelo["asignaciones"].items():
      print(f"{codigo}: {ambulancia}")
  else:
    print("no hay asignaciones por el momento")

def main ():
  modelo = crear_modelo()

  #emergencia 1
  m1 = percepcion("EM001","baja","zona 1")
  agente_basado_modelo(m1, modelo)


  #emergencia 2
  m2 = percepcion("EM002","alta","zona 7")
  agente_basado_modelo(m2, modelo)

  #liberar ambulancia
  liberar_ambulancia("AMB-01", m1, modelo)

  print(mostrar_estado(modelo))

if __name__ == "__main__":
  main()