# -*- coding: utf-8 -*-
"""Ejercicio_Sistema_Iluminacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tka1MltXVj6iSi_BAE-Rx6DU1X5rqJAO

Autor: Jairo Blanco
Codigo: 2024114040
Materia: Inteligencia Artificial
Tema: Agente Reactivo Simple
descripcion: Un salón universitario cuenta con sensores que detectan si hay personas presentes
y el nivel de iluminación. El agente debe decidir si enciende, mantiene o apaga las luces

Ahora implementaremos la funcion de percepción, la cual recibe y trata los parametros de entrada.
"""

def percepcion(presencia:bool,nivel_luz:str )->tuple[bool,str]:
  return presencia, nivel_luz

"""Ahora implementamos la logica del agente"""

def agente_reactivo(percepcion_datos: tuple[bool,str])->str:
  presencia, nivel_luz = percepcion_datos # desempaquetamos la tupla
  # regla 1, si hay presencia de personas y el nivel de luz es bajo, el agente decide encender luces
  if presencia and nivel_luz.lower() == "bajo":
    return "Encender luces"

  # regla 2, si hay presencia de personas y el nivel de luz es medio, mantener luces
  if presencia and nivel_luz.lower() == "medio":
    return "Mantener luces"

  # regla 3 y 4, si la luz está alta o no hay personas, apague las luces
  if nivel_luz.lower() == "alto" or not presencia:
    return "Apagar luces"

  return "No operar"

"""Implementamos el main donde usaremos el agente

"""

def main():
  presencia = False
  nivel_luz = "bajo"
  desicion = percepcion(presencia, nivel_luz) #probamos que desicion toma el agente con presencia y nivel fijos
  accion = agente_reactivo(desicion)
  print(accion) #imprimimos la acción

if __name__ == "__main__":
  main()