# -*- coding: utf-8 -*-
"""Ejercicio_Biblioteca_Universitaria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eas2U9804UCx-lAikwSFNZZ36RXLz7GQ

Autor: Jairo Blanco
Codigo: 2024114040
Materia: Inteligencia Artificial
Tema: Agente Basado en Modelo
Problema: La biblioteca cuenta con salas de estudio que pueden ser asignadas a estudiantes.
El agente debe recordar las reservas realizadas para evitar duplicaciones y mantener los cupos actualizados.

Definimos la funcion de creación para la BASE del agente
"""

def crear_modelo()->dict:
  modelo = {
    "cupos": {
        "A": 2,
        "B": 3,
        "C": 2
    },
    "reservas": {}
  }

  return modelo

"""Definimos la percepcion del agente"""

def percepcion(codigo_estudiante: str, tipo_grupo: str)->tuple[str,str]:
  return codigo_estudiante, tipo_grupo

"""ahora creamos la logica del agente"""

def agente_biblioteca(percepcion_actual: tuple[str,str], modelo: dict)->None:
  codigo, tipo_grupo = percepcion_actual
  grupo = tipo_grupo.lower()


  #si el estudiante ya tiene una reserva, informamos la sala que ya está reservada
  if codigo in modelo["reservas"]:
    sala = modelo["reservas"][codigo] #si el codigo está, extraemos la sala que fue reservada por el mismo
    print("el estudiante de codigo ", codigo , " ya tiene reservada la sala: ", sala)
    return

  #si el grupo es individual y la sala A tiene disponibilidad reservar la sala A
  if grupo == "individual":
    if modelo["cupos"]["A"]>0:
      modelo["cupos"]["A"]-=1
      modelo["reservas"][codigo] = "A"
      print("el estudiante de codigo ", codigo , " reservó la sala A para él solo")
      return
  #si el grupo es pequeño y la sala B tiene disponibilidad reservar sala B
  if grupo == "pequeño":
    if modelo["cupos"]["B"]>0:
      modelo["cupos"]["B"]-=1
      modelo["reservas"][codigo] = "B"
      print("el estudiante de codigo ", codigo , " reservó la sala B para un grupo pequeño")
      return
  #si el grupo es grande y la sala C tiene disponibilidad reservar sala C
  if grupo == "grande":
    if modelo["cupos"]["C"]>0:
      modelo["cupos"]["C"]-=1
      modelo["reservas"][codigo] = "C"
      print("el estudiante de codigo ", codigo , " reservó la sala C para un grupo grande")
      return

  #si ninguna se cumple intentar reservar cualquiera de las otras
  for sala, cupos in modelo["cupos"].items():
    if cupos>0 and sala != "A": #recorremos las salas y si alguna tiene cupo, la asignamos excepto a la sala A
      modelo["cupos"][sala]-=1
      modelo["reservas"][codigo] = sala
      print("el estudiante de codigo ", codigo , " reservó la sala ", sala)
    else:
      print("reserva rechazada, no hay salas disponibles")

"""Implementamos Cancelar reserva"""

def cancelar_reserva(codigo_estudiante: str, modelo: dict)->None:
  if codigo_estudiante in modelo["reservas"]: # primero verificamos que el estudiante tenga una reserva
    sala = modelo["reservas"][codigo_estudiante] # sacamos la sala que reservó el estudiante
    modelo["cupos"][sala]+=1 # luego reestablecemos el cupo de la sala que habiamos reservado antes
    del modelo["reservas"][codigo_estudiante] # borramos la reserva
    print("el estudiante de codigo ", codigo_estudiante , " canceló su reserva en la sala ", sala)
  else:
    print("el estudiante ",codigo_estudiante," no tiene ninguna reserva") #si no tiene reservas, no podemos eliminar nada, por lo que solo imprimimos que no tiene reservas

"""Ahora mostramos el estado del agente"""

def mostrar_estado(modelo:dict)->None:
  print("cupos disponibles: ")
  for sala, cupos in modelo["cupos"].items():
    print(f"{sala}: {cupos}")
  print("\nreservas: ")
  if len(modelo["reservas"])==0:
    print("no hay reservas")
  else:
    for codigo, sala in modelo["reservas"].items():
      print(f"{codigo}: {sala}")

"""Luego vemos el main, definimos percepciones de prueba y mostramos el estado"""

def main():
  modelo = crear_modelo()

  #reserva 1
  r1 = percepcion("20241002","individual")
  agente_biblioteca(r1,modelo)

  #reserva 2
  r2 = percepcion("20241003","pequeño")
  agente_biblioteca(r2,modelo)

  #reserva 3
  r3 = percepcion("20241004","grande")
  agente_biblioteca(r3,modelo)

  #cancelamos la reserva 1
  cancelar_reserva("20241002",modelo)

  #reserva 4
  r4 = percepcion("20241005","pequeño")
  agente_biblioteca(r4,modelo)

  #mostramos el estado del modelo
  mostrar_estado(modelo)

if __name__ == "__main__":
  main()