# -*- coding: utf-8 -*-
"""Parcial_Agente_Modelo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_RjomhyI7AtvkuKDmkFA6PpzZLK9v_WZ

Autor: Jairo Blanco
Codigo: 2024114040
Tema: Punto 10 parcial 1 - Agente Basado en Modelo

Una universidad dispone de tres tabletas para prestamo. Cada estudiante puede tener como maximo 1 tableta y una tableta prestada no puede ser asignada nuevamente hasta que sea devuelta.
"""

def crear_modelo()->dict:
  modelo = {
      "tabletas": {"TAB-01":"disponible","TAB-02":"disponible","TAB-03":"disponible"},
      "prestamos": set()
  }
  return modelo

"""ahora definimos la percepcion, a la cual ingresa solo el codigo del estudiante que quiere una tableta."""

def percepcion(codigo_estudiante: str):
  return codigo_estudiante

"""luego definimos la logica interna del agente, en este caso crearemos su unica funcion de aprendizaje (actualizacion) despues por peticion del enunciado del ejercicio."""

def agente_tabletas(percepcion_actual: str, modelo: dict):
  codigo = percepcion_actual
  #regla 1, si el estudiante ya tiene una tableta, informamos cual tiene asignada
  if codigo in modelo["prestamos"]:
    print("el estudiante ", codigo, " ya tiene una tableta asignada")
    return

  #regla 2, si existe una tableta disponible, la asignamos una vez sabido que el estudiante no posee tableta
  for tableta in modelo["tabletas"]: #iteramos las tabletas a ver cual esta disponible
    if modelo["tabletas"][tableta] == "disponible": #si encontramos una disponble la asignamos como prestada y luego añadimos el codigo del estudiante a los prestamos
      modelo["tabletas"][tableta] = "prestada"
      modelo["prestamos"].add(codigo)
      print("la tableta ", tableta, " fue prestada al estudiante ", codigo)
      return

  #regla 3, si iteramos en todas las tabletas y ninguna estuvo disponible, informamos
  print("lo sentimos, no existe disponibilidad de tabletas ahora mismo, intente en otro momento")

"""ahora creamos la unica función de aprendizaje solicitada, devolver_tableta(codigo, modelo) en donde debemos actualizar el estado nuevamente a disponible y quitar el codigo del estudiante de los prestamos"""

def devolver_tableta(codigo_estudiante: str, modelo: dict):
  for tableta in modelo["tabletas"]:
    if modelo["tabletas"][tableta] == "prestada":
      if codigo_estudiante in modelo["prestamos"]:
        modelo["tabletas"][tableta] = "disponible"
        print("la tableta", tableta, " fue devuelta al estudiante ", codigo_estudiante)
        modelo["prestamos"].remove(codigo_estudiante)
        return
      else:
        print("el estudiante no tenia ninguna tableta prestada")
        return

"""ahora mostramos el estado actual del agente, imrpimiendo el modelo iterativamente para que se vea bien:"""

def mostrar_estado(modelo: dict):
  for key in modelo:
    print(key, ":", modelo[key])

"""finalmente lo probamos:"""

def main():
  modelo = crear_modelo()

  codigo1 = percepcion("2024114040")
  agente_tabletas(codigo1, modelo)
  mostrar_estado(modelo)

  codigo2 = percepcion("2024114041")
  agente_tabletas(codigo2, modelo)
  mostrar_estado(modelo)

  codigo3 = percepcion("2024114042")
  agente_tabletas(codigo3, modelo)
  mostrar_estado(modelo)

  codigo4 = percepcion("2024114045")
  agente_tabletas(codigo4, modelo)
  mostrar_estado(modelo)

  devolver_tableta("2024114040", modelo)
  mostrar_estado(modelo)

if __name__ == "__main__":
  main()