# -*- coding: utf-8 -*-
"""Parcial_Agente_Simple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oMoRagy7MBriBfKzMxSrllDnE_BzWziP

Autor: Jairo Blanco
Codigo: 2024114040
Tema: Parcial punto 9
Correspondencia: el sistema corresponde a un agente reactivo simple porque solo es capaz de percibir ciertos datos del ecosistema / entorno a analizar y
toma UNA unica accion en base a los mismos, no reconoce historicos o aprende luego de recibir nuevas percepciones

Un laboratorio desea implementar un agente que controle la ventilacion usando unicamente la percepcion actual (datos que es capaz de obtener del entorno). Recibiendo:
"""

def percepcion(temperatura: float, personas: bool)->tuple[float,bool]:
  return temperatura, personas #empaquetamos en una estructura de datos para manejo de datos, en este caso una tupla

"""ahora creamos la logica interna del agente:"""

def agente_ventilacion(percepcion_actual: tuple[float,bool])->str:
  temperatura, personas = percepcion_actual
  if not personas: # regla 1, si no hay personas apagamos la ventilacion
    return "apagar ventilacion"

  # si el condicional de arriba no ha retornado es porque si hay personas, por lo que no es necesario volver a preguntar
  if temperatura < 20:
    return "mantener ventilacion apagada" # regla 2, si hay personas y la temperatura es menor que 20 mantenemos la ventilacion apagada

  # aca sucede lo mismo, no es necesario preguntar si es mayor a 20 porque el condicional de arriba tambien se encarga
  if temperatura < 27:
    return "activar ventilacion" # regla 3, si hay personas y la temperatura esta entre 20 y 27 activamos la ventilacion


  # tampoco es necesario preguntar si temperatura es mayor a 27 porque si no entró a ninguno de los if's es porque efectivamente es mayor a 27
  return "activar ventilacion maxima" #regla 4, si hay personas y la temperatura es mayor a 27 activamos ventilacion maxima

"""Ahora probamos la funcion en un main y vemos las acciones:"""

def main():
  temperatura1 = 12
  temperatura2 = 23
  temperatura3 = 40

  personas1 = True
  personas2 = False

  percepcion1 = percepcion(temperatura1, personas1) # 12 grados y hay personas
  percepcion2 = percepcion(temperatura2, personas1) # 23 grados y hay personas
  percepcion3 = percepcion(temperatura3, personas2) # 40 grados y no hay personas
  percepcion4 = percepcion(temperatura1, personas2) # 12 grados y no hay personas

  accion1 = agente_ventilacion(percepcion1)
  accion2 = agente_ventilacion(percepcion2)
  accion3 = agente_ventilacion(percepcion3)
  accion4 = agente_ventilacion(percepcion4)

  print(f"Percepcion 1: {percepcion1}")
  print(f"Accion 1: {accion1}")
  print(f"Percepcion 2: {percepcion2}")
  print(f"Accion 2: {accion2}")
  print(f"Percepcion 3: {percepcion3}")
  print(f"Accion 3: {accion3}")
  print(f"Percepcion 4: {percepcion4}")
  print(f"Accion 4: {accion4}")

if __name__ == "__main__":
  main()