# -*- coding: utf-8 -*-
"""Ejercicio_Control_Temperatura.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1baaV1ATnfddbLCdx2AQNiBEhR_ih5NXd

Autor: Jairo Blanco
Codigo: 2024114040
Materia: Inteligencia Artificial
Tema: Agente Reactivo Simple
descripcion: Diseñar un agente encargado de controlar el aire
acondicionado de un laboratorio de computadores. El agente observa únicamente la temperatura actual.

Diseñamos la percepcion para tratado de parametros
"""

def percepcion(temperatura:float)->float:
  return temperatura

"""ahora realizamos la logica del agente"""

def agente_simple(percepcion_actual:float)->str:
  temp = percepcion_actual
  #regla 1, si temperatura es menor que 18 grados, apagar el aire
  if temp < 18:
    return "Apagar aire acondicionado"

  # regla 2, si temperatura este entre 18 y 23, matener esa temperatura
  if temp <= 23:
    return "Mantener temperatura"

  # regla 3, si temperatura esta entre 24 y 28, encender el aire
  if temp <=28:
    return "Encender aire acondicionado"

  # regla 4, si temperatura es mayor a 28, activar refrigeración máxima
  return "Activar refrigeración máxima"

"""vamos a crear main para evaluar la logica"""

def main():
  temperatura = float(input("ingrese la temperatura actual: "))

  perc_actual = percepcion(temperatura)
  accion = agente_simple(perc_actual)
  print(accion)

if __name__ == "__main__":
  main()